import discord
from discord.ext import commands
import requests
import lxml
from bs4 import BeautifulSoup
import re
import config


bot = commands.Bot(command_prefix="!", intents=discord.Intents.all())
url = "https://raw.githubusercontent.com/IceQ1337/CS-RSS-Feed/master/feeds/updates-feed-en.xml"


@bot.event
async def on_ready():
    print("----------")
    print("bot is online")


def get_html_and_parse(url):
    # Send a GET request to the URL and get the HTML content
    response = requests.get(url)

    if response.status_code == 200:
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.text, "xml")
        entries = soup.find_all("item")

        if entries:
            latest_entry = entries[0]
            # Find different catergories in xml
            title = latest_entry.find("title")
            # print(title)

            description = latest_entry.find("description")

            if title:
                plain_text_desc = title.get_text()

            if description:
                description_text = description.get_text()

                description_soup = BeautifulSoup(description_text, "html.parser")

                plain_text = description_soup.get_text(separator="\n")

                lines = plain_text.split("\n")
                formatted_lines = []
                for line in lines:
                    # Match all [ HEADINGS ]
                    if re.match("^\s*\[[^\]]*\].*", line):
                        formatted_lines.append(line)
                    else:
                        formatted_lines.append("- " + line)

            else:
                print("No description found in the latest entry.")
        else:
            print("No entries found in the RSS feed.")
    else:
        print(f"Failed to fetch the HTML. Status code: {response.status_code}")
    # lines = trans
    shift = "\n".join(formatted_lines)
    title_cur = plain_text_desc
    return shift, title_cur


shift, title_cur = get_html_and_parse(url)


@bot.command()
async def embed(ctx, member: discord.Member = None):
    if member == None:
        member = ctx.author

    picture = "https://cdn-wp.thesportsrush.com/2023/09/8a83edd8-cs2.jpg?w=1920&q=60"
    embed = discord.Embed(title=f"{title_cur}", colour=discord.Colour.orange())
    embed.set_author(name=f"New Update Just Dropped!")
    embed.set_thumbnail(url=f"{picture}")
    embed.add_field(name=f"Here's what changed", value=f"{shift}", inline=True)

    embed.set_footer(
        text="Generated by cs2date",
        icon_url="https://img.icons8.com/color/144/restart--v1.png",
    )
    await ctx.send(embed=embed)


if __name__ == "__main__":
    try:
        intents = discord.Intents.all()
        intents.message_content = True
        client = discord.Client(intents=intents)
        bot.run(config.discord_token)

    except SystemExit:
        print("Shutting down :/")
